import json
import os

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<div style=\"\n",
    "    text-align: center; \n",
    "    background: linear-gradient(135deg, #0062ff 0%, #00d4ff 100%); \n",
    "    font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; \n",
    "    color: white; \n",
    "    padding: 35px 20px; \n",
    "    border-radius: 15px; \n",
    "    box-shadow: 0 10px 25px rgba(0, 98, 255, 0.3);\n",
    "    margin-bottom: 25px;\">\n",
    "    <div style=\"font-size: 35px; font-weight: 800; letter-spacing: 1.5px; text-transform: uppercase; line-height: 1.2;\">\n",
    "        Trực Quan Hóa Dữ Liệu - Lab 03\n",
    "    </div>\n",
    "    <div style=\"font-size: 16px; font-weight: 500; margin-top: 10px; font-style: italic; opacity: 0.9;\">\n",
    "        \"Xây dựng mô hình dữ liệu và trực quan hóa bằng Power BI\"\n",
    "    </div>\n",
    "    <div style=\"font-size: 18px; font-weight: 600; margin-top: 15px; border-top: 1px solid rgba(255,255,255,0.4); display: inline-block; padding-top: 10px; letter-spacing: 1px;\">\n",
    "        NHÓM 05 - FIT-HCMUS\n",
    "    </div>\n",
    "</div>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<div style=\"text-align: center; font-size: 40px; font-weight: bold;\">\n",
    "  TIỀN XỬ LÝ BỘ DỮ LIỆU TMDB MOVIES\n",
    "</div>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Giới thiệu và cấu hình ban đầu"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1.1. Mục tiêu tiền xử lý\n",
    "\n",
    "Dataset gốc chứa dữ liệu phim từ TMDB (The Movie Database). Nhóm tập trung nghiên cứu và so sánh các đặc điểm, mức độ phổ biến và đánh giá của các phim đến từ ba quốc gia: **Việt Nam**, **Hàn Quốc**, và **Trung Quốc** trong giai đoạn từ năm 2000 đến năm 2025.\n",
    "\n",
    "**Phạm vi và yêu cầu tiền xử lý:**\n",
    "- Lọc dữ liệu theo quốc gia sản xuất (chỉ giữ phim có quốc gia sản xuất chứa `Vietnam`, `South Korea`, hoặc `China`).\n",
    "- Lọc phim có năm phát hành trong khoảng 2000–2025 dựa trên cột `release_date`.\n",
    "- Chỉ giữ phim có dữ liệu chấm điểm hợp lệ (số điểm và số lượt đánh giá > 0) và có trạng thái `Released`.\n",
    "- Đổi tên cột sang tiếng Việt không dấu để phục vụ xây dựng mô hình dữ liệu trong Power BI.\n",
    "- Tạo các cờ kiểm tra chất lượng dữ liệu để phục vụ lọc/slicer trong báo cáo (không xóa dòng thiếu doanh thu/ngân sách/thời lượng).\n",
    "- Làm sạch ký tự xuống dòng đặc biệt trước khi export để tránh lỗi hiển thị.\n",
    "- Tách dữ liệu thành các bảng quan hệ Dim/Fact/Bridge phục vụ Import vào Power BI."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1.2. Import thư viện và cấu hình đường dẫn\n",
    "\n",
    "Nạp các thư viện cần thiết cho việc xử lý dữ liệu, đồng thời cấu hình các đường dẫn lưu trữ tệp dữ liệu đầu vào và các tệp kết quả đầu ra. Đường dẫn được cấu hình động để hoạt động chính xác dù chạy từ thư mục gốc hay thư mục chứa notebook."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import ast\n",
    "import json\n",
    "import os\n",
    "import re\n",
    "import time\n",
    "import pandas as pd\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "# Tai cac bien moi truong tu file .env neu co\n",
    "load_dotenv()\n",
    "\n",
    "# Tự động điều chỉnh đường dẫn nếu chạy từ thư mục gốc hoặc thư mục 'notebooks'\n",
    "if os.path.basename(os.getcwd()) == \"notebooks\":\n",
    "    RAW_DATA_PATH = \"../data/raw/TMDB_movie_dataset.csv\"\n",
    "    OUTPUT_CLEAN_PATH = \"../data/processed/tmdb_vn_kr_cn_2000_2025_scored.csv\"\n",
    "    POWERBI_DIR = \"../data/processed/powerbi/\"\n",
    "else:\n",
    "    RAW_DATA_PATH = \"data/raw/TMDB_movie_dataset.csv\"\n",
    "    OUTPUT_CLEAN_PATH = \"data/processed/tmdb_vn_kr_cn_2000_2025_scored.csv\"\n",
    "    POWERBI_DIR = \"data/processed/powerbi/\"\n",
    "\n",
    "# Tạo các thư mục đầu ra nếu chưa tồn tại\n",
    "os.makedirs(os.path.dirname(OUTPUT_CLEAN_PATH), exist_ok=True)\n",
    "os.makedirs(POWERBI_DIR, exist_ok=True)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1.3. Đọc dữ liệu thô và kiểm tra tổng quan\n",
    "\n",
    "Đọc tệp dữ liệu gốc, in kích thước dữ liệu (shape) và danh sách cột để xác minh dữ liệu đầu vào."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Đọc dữ liệu gốc từ file CSV\n",
    "df = pd.read_csv(RAW_DATA_PATH)\n",
    "\n",
    "print(f\"Shape ban đầu của dataset: {df.shape}\")\n",
    "print(\"\\nDanh sách các cột trong dữ liệu thô:\")\n",
    "print(df.columns.tolist())\n",
    "\n",
    "# Kiểm tra các cột bắt buộc cho phạm vi lọc ban đầu\n",
    "required_columns = [\n",
    "    \"production_countries\",\n",
    "    \"release_date\",\n",
    "    \"vote_average\",\n",
    "    \"vote_count\",\n",
    "]\n",
    "missing_columns = [col for col in required_columns if col not in df.columns]\n",
    "\n",
    "if missing_columns:\n",
    "    raise ValueError(f\"Thiếu các cột bắt buộc: {missing_columns}\")\n",
    "else:\n",
    "    print(\"\\nTất cả các cột bắt buộc đều tồn tại.\")\n",
    "\n",
    "display(df.head())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Lọc dữ liệu theo phạm vi nghiên cứu"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2.1. Lọc theo quốc gia sản xuất\n",
    "\n",
    "Lọc theo cột `production_countries`, chỉ giữ lại các phim có quốc gia sản xuất chứa `Vietnam`, `South Korea`, hoặc `China`. Đối với `China`, không bao gồm `Hong Kong`, `Taiwan`, `Macau` làm một phần của nhóm China, trừ khi phim đó đồng thời đồng sản xuất với `China`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "TARGET_COUNTRIES = [\"Vietnam\", \"South Korea\", \"China\"]\n",
    "TARGET_COUNTRY_SET = set(TARGET_COUNTRIES)\n",
    "\n",
    "\n",
    "def _is_missing(value):\n",
    "    \"\"\"Kiểm tra giá trị thiếu mà không làm lỗi với list/dict.\"\"\"\n",
    "    if value is None:\n",
    "        return True\n",
    "    if isinstance(value, float) and pd.isna(value):\n",
    "        return True\n",
    "    return False\n",
    "\n",
    "\n",
    "def _parse_json_like_text(value):\n",
    "    \"\"\"Thử chuyển chuỗi JSON/list/dict thành object Python.\"\"\"\n",
    "    if not isinstance(value, str):\n",
    "        return value\n",
    "\n",
    "    text = value.strip()\n",
    "    if not text:\n",
    "        return []\n",
    "\n",
    "    for parser in (json.loads, ast.literal_eval):\n",
    "        try:\n",
    "            return parser(text)\n",
    "        except (ValueError, SyntaxError, TypeError, json.JSONDecodeError):\n",
    "            continue\n",
    "\n",
    "    return text\n",
    "\n",
    "\n",
    "def extract_country_names(value):\n",
    "    \"\"\"Trích xuất tên quốc gia từ null, text, list hoặc chuỗi JSON-like.\"\"\"\n",
    "    if _is_missing(value):\n",
    "        return []\n",
    "\n",
    "    parsed_value = _parse_json_like_text(value)\n",
    "    country_names = []\n",
    "\n",
    "    def collect_country_name(item):\n",
    "        if _is_missing(item):\n",
    "            return\n",
    "\n",
    "        if isinstance(item, dict):\n",
    "            name = item.get(\"name\") or item.get(\"country\") or item.get(\"english_name\")\n",
    "            if name:\n",
    "                country_names.append(str(name).strip())\n",
    "            return\n",
    "\n",
    "        if isinstance(item, list):\n",
    "            for child_item in item:\n",
    "                collect_country_name(child_item)\n",
    "            return\n",
    "\n",
    "        if isinstance(item, str):\n",
    "            text = item.strip()\n",
    "            if not text:\n",
    "                return\n",
    "\n",
    "            parsed_text = _parse_json_like_text(text)\n",
    "            if parsed_text is not text:\n",
    "                collect_country_name(parsed_text)\n",
    "                return\n",
    "\n",
    "            # Tách chuỗi văn bản thường theo các dấu phân cách phổ biến.\n",
    "            for name in re.split(r\"[,;/|]\", text):\n",
    "                clean_name = name.strip()\n",
    "                if clean_name:\n",
    "                    country_names.append(clean_name)\n",
    "\n",
    "    collect_country_name(parsed_value)\n",
    "\n",
    "    # Loại trùng nhưng giữ nguyên thứ tự xuất hiện.\n",
    "    unique_country_names = []\n",
    "    seen = set()\n",
    "    for name in country_names:\n",
    "        normalized_name = name.casefold()\n",
    "        if normalized_name not in seen:\n",
    "            unique_country_names.append(name)\n",
    "            seen.add(normalized_name)\n",
    "\n",
    "    return unique_country_names\n",
    "\n",
    "\n",
    "def get_selected_countries(value):\n",
    "    \"\"\"Chỉ giữ các quốc gia thuộc phạm vi nghiên cứu (Vietnam, South Korea, China).\"\"\"\n",
    "    country_names = extract_country_names(value)\n",
    "    selected = [c for c in country_names if c in TARGET_COUNTRY_SET]\n",
    "    return selected\n",
    "\n",
    "\n",
    "# Tạo các cột quốc gia để phục vụ lọc và phân tách bảng quan hệ sau này\n",
    "country_df = df.copy()\n",
    "country_df[\"selected_countries\"] = country_df[\"production_countries\"].apply(get_selected_countries)\n",
    "country_df[\"selected_countries_text\"] = country_df[\"selected_countries\"].apply(\n",
    "    lambda countries: \", \".join(countries)\n",
    ")\n",
    "country_df[\"primary_selected_country\"] = country_df[\"selected_countries\"].apply(\n",
    "    lambda countries: countries[0] if countries else pd.NA\n",
    ")\n",
    "\n",
    "# Lọc chỉ giữ phim có ít nhất 1 quốc gia trong danh sách được chọn\n",
    "filtered_country_df = country_df[country_df[\"selected_countries\"].str.len() > 0].copy()\n",
    "\n",
    "print(f\"Số dòng sau khi lọc quốc gia: {len(filtered_country_df):,}\")\n",
    "print(\"\\nPhân bố theo quốc gia chính (primary):\")\n",
    "print(filtered_country_df[\"primary_selected_country\"].value_counts(dropna=False))\n",
    "display(filtered_country_df[[\"title\", \"production_countries\", \"selected_countries_text\"]].head())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2.2. Lọc theo năm phát hành 2000–2025\n",
    "\n",
    "Chuyển đổi cột ngày phát hành sang kiểu dữ liệu datetime, trích xuất năm phát hành và thực hiện lọc phim được phát hành từ năm 2000 đến năm 2025."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Chuyển đổi ngày phát hành sang datetime và trích xuất năm phát hành\n",
    "filtered_country_df[\"release_date\"] = pd.to_datetime(\n",
    "    filtered_country_df[\"release_date\"],\n",
    "    errors=\"coerce\",\n",
    ")\n",
    "filtered_country_df[\"release_year\"] = filtered_country_df[\"release_date\"].dt.year\n",
    "\n",
    "# Đếm số dòng không thể chuyển đổi ngày phát hành\n",
    "invalid_release_date_count = filtered_country_df[\"release_date\"].isna().sum()\n",
    "print(f\"Số dòng không parse được release_date: {invalid_release_date_count:,}\")\n",
    "\n",
    "# Lọc phim phát hành trong giai đoạn 2000-2025\n",
    "filtered_year_df = filtered_country_df[\n",
    "    filtered_country_df[\"release_year\"].between(2000, 2025, inclusive=\"both\")\n",
    "].copy()\n",
    "filtered_year_df[\"release_year\"] = filtered_year_df[\"release_year\"].astype(\"Int64\")\n",
    "\n",
    "print(f\"Số dòng sau lọc năm phát hành 2000–2025: {len(filtered_year_df):,}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2.3. Lọc phim có dữ liệu chấm điểm và trạng thái Released\n",
    "\n",
    "Chỉ giữ lại những bộ phim có số điểm trung bình và số lượt đánh giá hợp lệ (> 0). Đồng thời, nếu tồn tại cột trạng thái, chỉ giữ phim ở trạng thái `Released`. Nếu không tồn tại cột trạng thái, chương trình sẽ in ra cảnh báo và bỏ qua bộ lọc trạng thái."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Chuyển dữ liệu đánh giá sang kiểu số\n",
    "filtered_year_df[\"vote_average\"] = pd.to_numeric(filtered_year_df[\"vote_average\"], errors=\"coerce\")\n",
    "filtered_year_df[\"vote_count\"] = pd.to_numeric(filtered_year_df[\"vote_count\"], errors=\"coerce\")\n",
    "\n",
    "# Lọc phim có dữ liệu chấm điểm\n",
    "filtered_score_df = filtered_year_df[\n",
    "    (filtered_year_df[\"vote_average\"].notna())\n",
    "    & (filtered_year_df[\"vote_count\"].notna())\n",
    "    & (filtered_year_df[\"vote_average\"] > 0)\n",
    "    & (filtered_year_df[\"vote_count\"] > 0)\n",
    "].copy()\n",
    "\n",
    "print(f\"Số dòng sau lọc dữ liệu chấm điểm: {len(filtered_score_df):,}\")\n",
    "\n",
    "# Lọc theo trạng thái phát hành Released\n",
    "if \"status\" in filtered_score_df.columns:\n",
    "    print(\"\\nPhân bố trạng thái phim trước khi lọc:\")\n",
    "    print(filtered_score_df[\"status\"].value_counts())\n",
    "\n",
    "    before_status_filter = len(filtered_score_df)\n",
    "    filtered_df = filtered_score_df[filtered_score_df[\"status\"] == \"Released\"].copy()\n",
    "\n",
    "    print(f\"\\nSố dòng trước lọc trạng thái: {before_status_filter:,}\")\n",
    "    print(f\"Số dòng sau lọc trạng thái Released: {len(filtered_df):,}\")\n",
    "else:\n",
    "    print(\"\\nCảnh báo: Cột 'status' không tồn tại trong dataset. Bỏ qua bước lọc trạng thái.\")\n",
    "    filtered_df = filtered_score_df.copy()\n",
    "\n",
    "print(f\"\\nSố dòng cuối cùng sau khi lọc: {len(filtered_df):,}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Chuẩn hóa và kiểm tra chất lượng dữ liệu"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3.1. Đổi tên thuộc tính sang tiếng Việt không dấu\n",
    "\n",
    "Đổi tên cột của dataset sang tiếng Việt không dấu giúp các thuộc tính trong mô hình dữ liệu của Power BI trở nên đồng bộ, dễ hiểu và dễ thao tác."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Từ điển đổi tên cột sang tiếng Việt không dấu\n",
    "rename_mapping = {\n",
    "    \"id\": \"MaPhim\",\n",
    "    \"title\": \"TenPhim\",\n",
    "    \"vote_average\": \"DiemDanhGiaTB\",\n",
    "    \"vote_count\": \"SoLuotDanhGia\",\n",
    "    \"status\": \"TrangThai\",\n",
    "    \"release_date\": \"NgayPhatHanh\",\n",
    "    \"revenue\": \"DoanhThu\",\n",
    "    \"runtime\": \"ThoiLuong\",\n",
    "    \"adult\": \"PhimNguoiLon\",\n",
    "    \"backdrop_path\": \"DuongDanAnhNen\",\n",
    "    \"budget\": \"NganSach\",\n",
    "    \"homepage\": \"TrangChu\",\n",
    "    \"imdb_id\": \"MaIMDb\",\n",
    "    \"original_language\": \"NgonNguGoc\",\n",
    "    \"original_title\": \"TenGoc\",\n",
    "    \"overview\": \"TomTatNoiDung\",\n",
    "    \"popularity\": \"DoPhoBien\",\n",
    "    \"poster_path\": \"DuongDanPoster\",\n",
    "    \"tagline\": \"CauGioiThieu\",\n",
    "    \"genres\": \"TheLoai\",\n",
    "    \"production_companies\": \"CongTySanXuat\",\n",
    "    \"production_countries\": \"QuocGiaSanXuat\",\n",
    "    \"spoken_languages\": \"NgonNguDuocNoi\",\n",
    "    \"keywords\": \"TuKhoa\",\n",
    "    \"release_year\": \"NamPhatHanh\",\n",
    "    \"selected_countries\": \"QuocGiaDuocChon\",\n",
    "    \"selected_countries_text\": \"QuocGiaDuocChonText\",\n",
    "    \"primary_selected_country\": \"QuocGiaChinh\",\n",
    "}\n",
    "\n",
    "# Chỉ đổi tên cột đang tồn tại trong dataset để tránh lỗi\n",
    "existing_rename_mapping = {\n",
    "    old_name: new_name\n",
    "    for old_name, new_name in rename_mapping.items()\n",
    "    if old_name in filtered_df.columns\n",
    "}\n",
    "\n",
    "filtered_df = filtered_df.rename(columns=existing_rename_mapping)\n",
    "\n",
    "print(\"Danh sách cột sau khi đổi tên:\")\n",
    "print(filtered_df.columns.tolist())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3.2. Xử lý tên phim hiển thị cho dashboard\n",
    "\n",
    "Tạo thêm cột `TenPhimHienThi` (giữ nguyên tên gốc ban đầu để không dịch tự động) và đánh dấu cờ `CanBoSungTenTiengAnh` nếu tên phim gốc chứa các ký tự đặc trưng của tiếng Trung/Hàn/Nhật (CJK). Điều này giúp người thiết kế dashboard sau này nhận diện được những phim cần bổ sung tên tiếng Anh thủ công để hiển thị đẹp mắt hơn."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def contains_cjk(text):\n",
    "    \"\"\"Kiểm tra xem chuỗi văn bản có chứa ký tự Trung/Hàn/Nhật (CJK) hay không.\"\"\"\n",
    "    if not isinstance(text, str):\n",
    "        return False\n",
    "    # Regular expression kiểm tra dải Unicode CJK\n",
    "    return bool(re.search(\n",
    "        r'[\\u4e00-\\u9fff\\u3400-\\u4dbf\\uac00-\\ud7af\\u3040-\\u309f\\u30a0-\\u30ff]',\n",
    "        text\n",
    "    ))\n",
    "\n",
    "\n",
    "# Tạo cột tên phim hiển thị (tạm thời giữ nguyên)\n",
    "filtered_df[\"TenPhimHienThi\"] = filtered_df[\"TenPhim\"]\n",
    "\n",
    "# Đánh dấu cờ cần bổ sung tên tiếng Anh\n",
    "filtered_df[\"CanBoSungTenTiengAnh\"] = filtered_df[\"TenPhim\"].apply(contains_cjk)\n",
    "\n",
    "print(f\"Tổng số phim cần bổ sung tên tiếng Anh (chứa ký tự CJK): {filtered_df['CanBoSungTenTiengAnh'].sum():,}\")\n",
    "if filtered_df[\"CanBoSungTenTiengAnh\"].sum() > 0:\n",
    "    print(\"\\nSố phim cần bổ sung tên tiếng Anh theo quốc gia chính:\")\n",
    "    print(filtered_df[filtered_df[\"CanBoSungTenTiengAnh\"]].groupby(\"QuocGiaChinh\").size())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3.3. Bổ sung các cờ kiểm tra chất lượng dữ liệu\n",
    "\n",
    "Thêm các thuộc tính cờ kiểm tra chất lượng dữ liệu để thuận tiện cho việc tạo slicer/filter trong Power BI mà **không loại bỏ các dòng bị thiếu thông tin tài chính/thời lượng**:\n",
    "- `DuSoLuotDanhGia`: Đạt ngưỡng tin cậy đánh giá (`SoLuotDanhGia >= 10`).\n",
    "- `CoDoanhThu`: `True` nếu `DoanhThu > 0` (các giá trị <= 0 được đưa về NaN).\n",
    "- `CoNganSach`: `True` nếu `NganSach > 0` (các giá trị <= 0 được đưa về NaN).\n",
    "- `ThoiLuongBatThuong`: `True` nếu phim có `ThoiLuong > 300` phút."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Tạo cờ đủ số lượt đánh giá\n",
    "filtered_df[\"DuSoLuotDanhGia\"] = filtered_df[\"SoLuotDanhGia\"] >= 10\n",
    "\n",
    "# Xử lý Doanh Thu\n",
    "if \"DoanhThu\" in filtered_df.columns:\n",
    "    filtered_df[\"DoanhThu\"] = pd.to_numeric(filtered_df[\"DoanhThu\"], errors=\"coerce\")\n",
    "    filtered_df.loc[filtered_df[\"DoanhThu\"] <= 0, \"DoanhThu\"] = pd.NA\n",
    "    filtered_df[\"CoDoanhThu\"] = filtered_df[\"DoanhThu\"].notna()\n",
    "else:\n",
    "    filtered_df[\"CoDoanhThu\"] = False\n",
    "\n",
    "# Xử lý Ngân Sách\n",
    "if \"NganSach\" in filtered_df.columns:\n",
    "    filtered_df[\"NganSach\"] = pd.to_numeric(filtered_df[\"NganSach\"], errors=\"coerce\")\n",
    "    filtered_df.loc[filtered_df[\"NganSach\"] <= 0, \"NganSach\"] = pd.NA\n",
    "    filtered_df[\"CoNganSach\"] = filtered_df[\"NganSach\"].notna()\n",
    "else:\n",
    "    filtered_df[\"CoNganSach\"] = False\n",
    "\n",
    "# Xử lý Thời Lượng\n",
    "if \"ThoiLuong\" in filtered_df.columns:\n",
    "    filtered_df[\"ThoiLuong\"] = pd.to_numeric(filtered_df[\"ThoiLuong\"], errors=\"coerce\")\n",
    "    filtered_df.loc[filtered_df[\"ThoiLuong\"] <= 0, \"ThoiLuong\"] = pd.NA\n",
    "    filtered_df[\"ThoiLuongBatThuong\"] = (\n",
    "        filtered_df[\"ThoiLuong\"].notna() & (filtered_df[\"ThoiLuong\"] > 300)\n",
    "    )\n",
    "else:\n",
    "    filtered_df[\"ThoiLuongBatThuong\"] = False\n",
    "\n",
    "print(\"Thống kê số lượng các cờ chất lượng dữ liệu:\")\n",
    "print(f\"  - Phim đủ lượt đánh giá (>= 10): {filtered_df['DuSoLuotDanhGia'].sum():,}\")\n",
    "print(f\"  - Phim có doanh thu hợp lệ:      {filtered_df['CoDoanhThu'].sum():,}\")\n",
    "print(f\"  - Phim có ngân sách hợp lệ:      {filtered_df['CoNganSach'].sum():,}\")\n",
    "print(f\"  - Phim có thời lượng bất thường:  {filtered_df['ThoiLuongBatThuong'].sum():,}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3.4. Làm sạch ký tự xuống dòng đặc biệt\n",
    "\n",
    "Chuẩn hóa các cột kiểu văn bản (như `TomTatNoiDung`, `CauGioiThieu`) bằng cách loại bỏ các ký tự xuống dòng đặc biệt (`\\u2028`, `\\u2029`, `\\r`, `\\n`, `\\t`) để tránh việc các phần mềm đọc dữ liệu (như VS Code, Power BI) nhận diện sai dòng hoặc cảnh báo lỗi \"Unusual line terminators\"."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def clean_text_value(value):\n",
    "    \"\"\"Thay thế ký tự xuống dòng lạ bằng khoảng trắng và gom khoảng trắng thừa.\"\"\"\n",
    "    if not isinstance(value, str):\n",
    "        return value\n",
    "\n",
    "    value = (\n",
    "        value.replace(\"\\u2028\", \" \")\n",
    "        .replace(\"\\u2029\", \" \")\n",
    "        .replace(\"\\r\", \" \")\n",
    "        .replace(\"\\n\", \" \")\n",
    "        .replace(\"\\t\", \" \")\n",
    "    )\n",
    "    # Gom các khoảng trắng liên tiếp thành 1 khoảng trắng và strip đầu cuối\n",
    "    value = re.sub(r\"\\s+\", \" \", value).strip()\n",
    "    return value\n",
    "\n",
    "\n",
    "# Áp dụng cho các cột text/object\n",
    "text_cols = filtered_df.select_dtypes(include=[\"object\"]).columns\n",
    "print(f\"Số cột text cần làm sạch: {len(text_cols)}\")\n",
    "print(f\"Danh sách các cột text: {text_cols.tolist()}\")\n",
    "\n",
    "for col in text_cols:\n",
    "    filtered_df[col] = filtered_df[col].apply(clean_text_value)\n",
    "\n",
    "print(\"\\nĐã hoàn tất làm sạch các ký tự xuống dòng đặc biệt.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3.5. Báo cáo kiểm tra chất lượng dữ liệu sau xử lý\n",
    "\n",
    "Xuất tệp dữ liệu sạch tổng thể `tmdb_vn_kr_cn_2000_2025_scored.csv` và in báo cáo thống kê tóm tắt chất lượng dữ liệu sau các bộ lọc để đảm bảo dữ liệu ổn định và phục vụ lưu trữ file clean tổng."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import datetime\n",
    "import requests\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "# Load environment variables\n",
    "load_dotenv()\n",
    "\n",
    "# 1. Khai báo đường dẫn lưu cache\n",
    "CACHE_DIR = os.path.join(os.path.dirname(OUTPUT_CLEAN_PATH), \"api_cache\")\n",
    "os.makedirs(CACHE_DIR, exist_ok=True)\n",
    "cache_path = os.path.join(CACHE_DIR, \"tmdb_movie_details_cache.json\")\n",
    "\n",
    "# Đọc cache hiện tại\n",
    "if os.path.exists(cache_path):\n",
    "    try:\n",
    "        with open(cache_path, \"r\", encoding=\"utf-8\") as f:\n",
    "            api_cache = json.load(f)\n",
    "    except Exception as e:\n",
    "        print(f\"Lỗi khi đọc tệp cache: {e}\")\n",
    "        api_cache = {}\n",
    "else:\n",
    "    api_cache = {}\n",
    "\n",
    "# 2. Xác định các bộ phim cần gọi API để bổ sung\n",
    "# CanBoSungTenTiengAnh == True, hoặc thiếu TomTatNoiDung, hoặc thiếu ThoiLuong, hoặc thiếu MaIMDb\n",
    "need_enrich_mask = (\n",
    "    (filtered_df[\"CanBoSungTenTiengAnh\"] == True)\n",
    "    | (filtered_df[\"TomTatNoiDung\"].isna())\n",
    "    | (filtered_df[\"TomTatNoiDung\"].fillna(\"\").str.strip() == \"\")\n",
    "    | (filtered_df[\"ThoiLuong\"].isna())\n",
    "    | (filtered_df[\"MaIMDb\"].isna())\n",
    "    | (filtered_df[\"MaIMDb\"].fillna(\"\").str.strip() == \"\")\n",
    ")\n",
    "total_needed = need_enrich_mask.sum()\n",
    "print(f\"Tổng số phim cần bổ sung thông tin: {total_needed}\")\n",
    "\n",
    "# 3. Cấu hình xác thực API\n",
    "bearer_token = os.environ.get(\"TMDB_BEARER_TOKEN\")\n",
    "api_key = os.environ.get(\"TMDB_API_KEY\")\n",
    "auth_method = \"None\"\n",
    "headers = {}\n",
    "\n",
    "if bearer_token:\n",
    "    headers[\"Authorization\"] = f\"Bearer {bearer_token}\"\n",
    "    auth_method = \"Bearer token\"\n",
    "    print(\"Phương thức xác thực đang dùng: Bearer token\")\n",
    "elif api_key:\n",
    "    auth_method = \"API key\"\n",
    "    print(\"Phương thức xác thực đang dùng: API key\")\n",
    "else:\n",
    "    auth_method = \"Khong co xac thuc, chi dung cache\"\n",
    "    print(\"Cảnh báo: Không tìm thấy TMDB_BEARER_TOKEN hay TMDB_API_KEY. Bỏ qua bước gọi API mới, chỉ sử dụng dữ liệu sẵn có trong cache.\")\n",
    "\n",
    "# 4. Thực hiện gọi API\n",
    "cache_updated = False\n",
    "success_count = 0\n",
    "cache_hit_count = 0\n",
    "error_count = 0\n",
    "not_found_count = 0\n",
    "api_results = {}\n",
    "\n",
    "for idx, row in filtered_df.iterrows():\n",
    "    movie_id = str(row[\"MaPhim\"])\n",
    "    \n",
    "    # Kiểm tra xem phim có thuộc diện cần bổ sung không\n",
    "    is_needed = (\n",
    "        (row[\"CanBoSungTenTiengAnh\"] == True)\n",
    "        or pd.isna(row[\"TomTatNoiDung\"])\n",
    "        or (isinstance(row[\"TomTatNoiDung\"], str) and row[\"TomTatNoiDung\"].strip() == \"\")\n",
    "        or pd.isna(row[\"ThoiLuong\"])\n",
    "        or pd.isna(row[\"MaIMDb\"])\n",
    "        or (isinstance(row[\"MaIMDb\"], str) and row[\"MaIMDb\"].strip() == \"\")\n",
    "    )\n",
    "    \n",
    "    if not is_needed:\n",
    "        continue\n",
    "        \n",
    "    # Nếu đã có trong cache, sử dụng luôn\n",
    "    if movie_id in api_cache:\n",
    "        api_results[movie_id] = api_cache[movie_id]\n",
    "        cache_hit_count += 1\n",
    "        processed = cache_hit_count + success_count + error_count + not_found_count\n",
    "        if processed % 100 == 0:\n",
    "            print(f\"Đã xử lý {processed}/{total_needed} phim...\")\n",
    "        continue\n",
    "        \n",
    "    # Nếu chưa có trong cache và có phương thức xác thực hợp lệ, thực hiện gọi API\n",
    "    if auth_method != \"Khong co xac thuc, chi dung cache\":\n",
    "        if auth_method == \"Bearer token\":\n",
    "            url = f\"https://api.themoviedb.org/3/movie/{movie_id}?language=en-US\"\n",
    "            req_headers = headers\n",
    "            req_params = {}\n",
    "        else: # API key\n",
    "            url = f\"https://api.themoviedb.org/3/movie/{movie_id}\"\n",
    "            req_headers = {}\n",
    "            req_params = {\"api_key\": api_key, \"language\": \"en-US\"}\n",
    "            \n",
    "        try:\n",
    "            time.sleep(0.2) # Delay nhẹ 200ms\n",
    "            response = requests.get(url, headers=req_headers, params=req_params, timeout=10)\n",
    "            if response.status_code == 200:\n",
    "                data = response.json()\n",
    "                api_cache[movie_id] = {\n",
    "                    \"status\": \"success\",\n",
    "                    \"data\": data,\n",
    "                    \"timestamp\": datetime.datetime.now().isoformat()\n",
    "                }\n",
    "                api_results[movie_id] = api_cache[movie_id]\n",
    "                cache_updated = True\n",
    "                success_count += 1\n",
    "            elif response.status_code == 404:\n",
    "                # 404 Not Found, cache lại để tránh gọi lặp lại\n",
    "                api_cache[movie_id] = {\n",
    "                    \"status\": \"not_found\",\n",
    "                    \"data\": None,\n",
    "                    \"timestamp\": datetime.datetime.now().isoformat()\n",
    "                }\n",
    "                api_results[movie_id] = api_cache[movie_id]\n",
    "                cache_updated = True\n",
    "                not_found_count += 1\n",
    "            else:\n",
    "                print(f\"Lỗi API với phim ID {movie_id}: HTTP {response.status_code}\")\n",
    "                error_count += 1\n",
    "        except Exception as e:\n",
    "            print(f\"Lỗi kết nối khi gọi API cho phim ID {movie_id}: {e}\")\n",
    "            error_count += 1\n",
    "    else:\n",
    "        # Không có token/key và không có trong cache -> Không thực hiện ghi nhận API\n",
    "        pass\n",
    "        \n",
    "    # In tiến trình xử lý\n",
    "    processed = cache_hit_count + success_count + error_count + not_found_count\n",
    "    if processed % 100 == 0:\n",
    "        print(f\"Đã xử lý {processed}/{total_needed} phim...\")\n",
    "        \n",
    "    # Ghi cache tạm thời định kỳ mỗi 100 phim để tránh mất dữ liệu nếu dừng giữa chừng\n",
    "    if cache_updated and (success_count + not_found_count) % 100 == 0:\n",
    "        try:\n",
    "            with open(cache_path, \"w\", encoding=\"utf-8\") as f:\n",
    "                json.dump(api_cache, f, ensure_ascii=False, indent=1)\n",
    "            print(f\"Đã lưu cache tạm thời (gọi thành công: {success_count}, 404: {not_found_count})...\")\n",
    "        except Exception:\n",
    "            pass\n",
    "\n",
    "# Ghi cache ra file nếu có cập nhật mới\n",
    "if cache_updated:\n",
    "    try:\n",
    "        with open(cache_path, \"w\", encoding=\"utf-8\") as f:\n",
    "            json.dump(api_cache, f, ensure_ascii=False, indent=1)\n",
    "        print(\"Đã cập nhật tệp cache mới.\")\n",
    "    except Exception as e:\n",
    "        print(f\"Lỗi khi ghi tệp cache: {e}\")\n",
    "\n",
    "# 5. Khởi tạo các cột mới và điền dữ liệu từ API dùng pandas Series\n",
    "filtered_df[\"TenPhimTiengAnh\"] = pd.Series([pd.NA] * len(filtered_df), index=filtered_df.index, dtype=\"object\")\n",
    "filtered_df[\"TomTatNoiDungTiengAnh\"] = pd.Series([pd.NA] * len(filtered_df), index=filtered_df.index, dtype=\"object\")\n",
    "filtered_df[\"ThoiLuongAPI\"] = pd.Series([pd.NA] * len(filtered_df), index=filtered_df.index, dtype=\"Int64\")\n",
    "filtered_df[\"NganSachAPI\"] = pd.Series([pd.NA] * len(filtered_df), index=filtered_df.index, dtype=\"Int64\")\n",
    "filtered_df[\"DoanhThuAPI\"] = pd.Series([pd.NA] * len(filtered_df), index=filtered_df.index, dtype=\"Int64\")\n",
    "filtered_df[\"MaIMDbAPI\"] = pd.Series([pd.NA] * len(filtered_df), index=filtered_df.index, dtype=\"object\")\n",
    "filtered_df[\"DaBoSungTuAPI\"] = False\n",
    "filtered_df[\"NguonBoSung\"] = pd.Series([pd.NA] * len(filtered_df), index=filtered_df.index, dtype=\"object\")\n",
    "filtered_df[\"ThoiDiemBoSung\"] = pd.Series([pd.NA] * len(filtered_df), index=filtered_df.index, dtype=\"object\")\n",
    "\n",
    "for idx, row in filtered_df.iterrows():\n",
    "    movie_id = str(row[\"MaPhim\"])\n",
    "    if movie_id in api_results:\n",
    "        res = api_results[movie_id]\n",
    "        if res[\"status\"] == \"success\" and res[\"data\"]:\n",
    "            data = res[\"data\"]\n",
    "            filtered_df.at[idx, \"TenPhimTiengAnh\"] = data.get(\"title\")\n",
    "            filtered_df.at[idx, \"TomTatNoiDungTiengAnh\"] = data.get(\"overview\")\n",
    "            \n",
    "            runtime = data.get(\"runtime\")\n",
    "            if runtime and runtime > 0:\n",
    "                filtered_df.at[idx, \"ThoiLuongAPI\"] = runtime\n",
    "                \n",
    "            budget = data.get(\"budget\")\n",
    "            if budget and budget > 0:\n",
    "                filtered_df.at[idx, \"NganSachAPI\"] = budget\n",
    "                \n",
    "            revenue = data.get(\"revenue\")\n",
    "            if revenue and revenue > 0:\n",
    "                filtered_df.at[idx, \"DoanhThuAPI\"] = revenue\n",
    "                \n",
    "            imdb_id = data.get(\"imdb_id\")\n",
    "            if imdb_id:\n",
    "                filtered_df.at[idx, \"MaIMDbAPI\"] = imdb_id\n",
    "                \n",
    "            filtered_df.at[idx, \"DaBoSungTuAPI\"] = True\n",
    "            filtered_df.at[idx, \"NguonBoSung\"] = \"TMDB API\"\n",
    "            filtered_df.at[idx, \"ThoiDiemBoSung\"] = res.get(\"timestamp\")\n",
    "\n",
    "# 6. Tạo các cột tổng hợp phân tích tích hợp\n",
    "# 6.1. Tên phim hiển thị cuối cùng\n",
    "filtered_df[\"TenPhimHienThiCuoi\"] = filtered_df[\"TenPhimTiengAnh\"].fillna(filtered_df[\"TenPhimHienThi\"]).fillna(filtered_df[\"TenPhim\"])\n",
    "\n",
    "# 6.2. Thời lượng phân tích\n",
    "filtered_df[\"ThoiLuongPhanTich\"] = filtered_df[\"ThoiLuong\"].fillna(filtered_df[\"ThoiLuongAPI\"])\n",
    "filtered_df[\"ThoiLuongPhanTich\"] = filtered_df[\"ThoiLuongPhanTich\"].astype(\"Int64\")\n",
    "\n",
    "filtered_df[\"NguonThoiLuong\"] = \"Không có\"\n",
    "filtered_df.loc[filtered_df[\"ThoiLuongAPI\"].notna(), \"NguonThoiLuong\"] = \"API\"\n",
    "filtered_df.loc[filtered_df[\"ThoiLuong\"].notna(), \"NguonThoiLuong\"] = \"Gốc\"\n",
    "\n",
    "# 6.3. Ngân sách và Doanh thu phân tích\n",
    "filtered_df[\"NganSachPhanTich\"] = filtered_df[\"NganSach\"].fillna(filtered_df[\"NganSachAPI\"])\n",
    "filtered_df[\"NganSachPhanTich\"] = filtered_df[\"NganSachPhanTich\"].astype(\"Int64\")\n",
    "\n",
    "filtered_df[\"NguonNganSach\"] = \"Không có\"\n",
    "filtered_df.loc[filtered_df[\"NganSachAPI\"].notna(), \"NguonNganSach\"] = \"API\"\n",
    "filtered_df.loc[filtered_df[\"NganSach\"].notna(), \"NguonNganSach\"] = \"Gốc\"\n",
    "\n",
    "filtered_df[\"DoanhThuPhanTich\"] = filtered_df[\"DoanhThu\"].fillna(filtered_df[\"DoanhThuAPI\"])\n",
    "filtered_df[\"DoanhThuPhanTich\"] = filtered_df[\"DoanhThuPhanTich\"].astype(\"Int64\")\n",
    "\n",
    "filtered_df[\"NguonDoanhThu\"] = \"Không có\"\n",
    "filtered_df.loc[filtered_df[\"DoanhThuAPI\"].notna(), \"NguonDoanhThu\"] = \"API\"\n",
    "filtered_df.loc[filtered_df[\"DoanhThu\"].notna(), \"NguonDoanhThu\"] = \"Gốc\"\n",
    "\n",
    "# 7. Xuất file enriched tổng hợp\n",
    "OUTPUT_ENRICHED_PATH = os.path.join(os.path.dirname(OUTPUT_CLEAN_PATH), \"tmdb_vn_kr_cn_2000_2025_enriched.csv\")\n",
    "filtered_df.to_csv(\n",
    "    OUTPUT_ENRICHED_PATH,\n",
    "    index=False,\n",
    "    encoding=\"utf-8-sig\",\n",
    "    lineterminator=\"\\n\"\n",
    ")\n",
    "\n",
    "# 8. In thống kê\n",
    "has_title_en = filtered_df[\"TenPhimTiengAnh\"].notna().sum()\n",
    "has_overview_en = filtered_df[\"TomTatNoiDungTiengAnh\"].notna().sum()\n",
    "has_runtime = filtered_df[\"ThoiLuongAPI\"].notna().sum()\n",
    "has_budget_rev = (filtered_df[\"NganSachAPI\"].notna() | filtered_df[\"DoanhThuAPI\"].notna()).sum()\n",
    "\n",
    "print(\"Thống kê làm giàu dữ liệu bằng TMDB API:\")\n",
    "print(f\"  - Số phim cần gọi API: {total_needed}\")\n",
    "print(f\"  - Số phim lấy từ cache: {cache_hit_count}\")\n",
    "print(f\"  - Số phim gọi API thành công: {success_count}\")\n",
    "print(f\"  - Số phim lỗi API: {error_count}\")\n",
    "print(f\"  - Số phim 404/not found: {not_found_count}\")\n",
    "print(f\"  - Số phim bổ sung được TenPhimTiengAnh: {has_title_en}\")\n",
    "print(f\"  - Số phim bổ sung được TomTatNoiDungTiengAnh: {has_overview_en}\")\n",
    "print(f\"  - Số phim bổ sung được ThoiLuongAPI: {has_runtime}\")\n",
    "print(f\"  - Số phim bổ sung được DoanhThuAPI/NganSachAPI: {has_budget_rev}\")\n",
    "print(f\"  - Đã xuất tệp enriched thành công tại: {OUTPUT_ENRICHED_PATH}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Tách dữ liệu thành các bảng quan hệ cho Power BI"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 4.1. Tạo bảng DimPhim\n",
    "\n",
    "Bảng `DimPhim` chứa các thông tin mô tả chi tiết của từng bộ phim. Khóa chính là `MaPhim` (được đảm bảo là duy nhất và không bị trùng lặp)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Các thuộc tính thuộc bảng DimPhim\n",
    "dim_phim_cols = [\n",
    "    \"MaPhim\",\n",
    "    \"TenPhim\",\n",
    "    \"TenPhimHienThi\",\n",
    "    \"TenGoc\",\n",
    "    \"TenPhimTiengAnh\",\n",
    "    \"TenPhimHienThiCuoi\",\n",
    "    \"TomTatNoiDung\",\n",
    "    \"TomTatNoiDungTiengAnh\",\n",
    "    \"CauGioiThieu\",\n",
    "    \"TrangThai\",\n",
    "    \"PhimNguoiLon\",\n",
    "    \"NgonNguGoc\",\n",
    "    \"TrangChu\",\n",
    "    \"MaIMDb\",\n",
    "    \"MaIMDbAPI\",\n",
    "    \"DuongDanPoster\",\n",
    "    \"DuongDanAnhNen\",\n",
    "    \"CanBoSungTenTiengAnh\",\n",
    "    \"DaBoSungTuAPI\",\n",
    "    \"NguonBoSung\",\n",
    "]\n",
    "\n",
    "# Chỉ lấy những cột tồn tại thực tế\n",
    "existing_dim_phim_cols = [col for col in dim_phim_cols if col in filtered_df.columns]\n",
    "\n",
    "# Tạo bảng DimPhim và loại bỏ trùng lặp theo MaPhim\n",
    "dim_phim = filtered_df[existing_dim_phim_cols].copy()\n",
    "dim_phim = dim_phim.drop_duplicates(subset=[\"MaPhim\"])\n",
    "\n",
    "print(f\"Kích thước bảng DimPhim: {dim_phim.shape}\")\n",
    "print(f\"Số lượng MaPhim duy nhất: {dim_phim['MaPhim'].nunique()}\")\n",
    "display(dim_phim.head())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 4.2. Tạo bảng FactHieuSuatPhim\n",
    "\n",
    "Bảng `FactHieuSuatPhim` chứa các chỉ số đo lường hiệu suất của phim như đánh giá, doanh thu, ngân sách, độ phổ biến, thời lượng, và các biến phân loại được tính toán thêm. Yêu cầu `MaPhim` không được chứa giá trị null và không bị trùng lặp.\n",
    "\n",
    "**Các biến tính toán bổ sung:**\n",
    "- `LoiNhuan` = `DoanhThuPhanTich` - `NganSachPhanTich` (chỉ tính khi cả hai giá trị hợp lệ).\n",
    "- `TySuatDoanhThuNganSach` = `DoanhThuPhanTich` / `NganSachPhanTich` (chỉ tính khi cả hai giá trị hợp lệ).\n",
    "- `CoThoiLuong`: `True` nếu thời lượng phân tích không null.\n",
    "- Các cột phân nhóm `NhomDiemDanhGia`, `NhomDoPhoBien`, `NhomThoiLuong`, `NhomDoanhThu` được chia theo phân vị (quantile) với cơ chế fallback an toàn nếu gặp lỗi `qcut` do trùng lặp hoặc thiếu dữ liệu. Toàn bộ các cờ chất lượng và phân nhóm đều dựa trên các cột phân tích tích hợp mới."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Danh sách các cột thuộc FactHieuSuatPhim ban đầu\n",
    "fact_cols = [\n",
    "    \"MaPhim\",\n",
    "    \"NgayPhatHanh\",\n",
    "    \"NamPhatHanh\",\n",
    "    \"DiemDanhGiaTB\",\n",
    "    \"SoLuotDanhGia\",\n",
    "    \"DuSoLuotDanhGia\",\n",
    "    \"DoPhoBien\",\n",
    "    \"ThoiLuong\",\n",
    "    \"ThoiLuongAPI\",\n",
    "    \"ThoiLuongPhanTich\",\n",
    "    \"NguonThoiLuong\",\n",
    "    \"NganSach\",\n",
    "    \"NganSachAPI\",\n",
    "    \"NganSachPhanTich\",\n",
    "    \"NguonNganSach\",\n",
    "    \"DoanhThu\",\n",
    "    \"DoanhThuAPI\",\n",
    "    \"DoanhThuPhanTich\",\n",
    "    \"NguonDoanhThu\",\n",
    "]\n",
    "existing_fact_cols = [col for col in fact_cols if col in filtered_df.columns]\n",
    "\n",
    "# Khởi tạo bảng fact từ filtered_df\n",
    "fact_hieu_suat = filtered_df[existing_fact_cols].copy()\n",
    "\n",
    "# Kiểm tra MaPhim không null và không trùng lặp\n",
    "fact_hieu_suat = fact_hieu_suat.dropna(subset=[\"MaPhim\"])\n",
    "fact_hieu_suat = fact_hieu_suat.drop_duplicates(subset=[\"MaPhim\"])\n",
    "\n",
    "# 1. Tính toán LoiNhuan và TySuatDoanhThuNganSach dùng các cột phân tích\n",
    "fact_hieu_suat[\"LoiNhuan\"] = fact_hieu_suat[\"DoanhThuPhanTich\"] - fact_hieu_suat[\"NganSachPhanTich\"]\n",
    "fact_hieu_suat[\"TySuatDoanhThuNganSach\"] = fact_hieu_suat[\"DoanhThuPhanTich\"] / fact_hieu_suat[\"NganSachPhanTich\"]\n",
    "\n",
    "# 2. Cờ CoThoiLuong, CoNganSach, CoDoanhThu và ThoiLuongBatThuong từ các trường phân tích\n",
    "fact_hieu_suat[\"CoThoiLuong\"] = fact_hieu_suat[\"ThoiLuongPhanTich\"].notna()\n",
    "fact_hieu_suat[\"CoNganSach\"] = fact_hieu_suat[\"NganSachPhanTich\"].notna()\n",
    "fact_hieu_suat[\"CoDoanhThu\"] = fact_hieu_suat[\"DoanhThuPhanTich\"].notna()\n",
    "fact_hieu_suat[\"ThoiLuongBatThuong\"] = (\n",
    "    fact_hieu_suat[\"ThoiLuongPhanTich\"].notna() & (fact_hieu_suat[\"ThoiLuongPhanTich\"] > 300)\n",
    ")\n",
    "\n",
    "# 3. Phân nhóm điểm đánh giá (NhomDiemDanhGia)\n",
    "try:\n",
    "    fact_hieu_suat[\"NhomDiemDanhGia\"] = pd.qcut(\n",
    "        fact_hieu_suat[\"DiemDanhGiaTB\"],\n",
    "        q=[0, 0.25, 0.75, 1.0],\n",
    "        labels=[\"Thap\", \"Trung binh\", \"Cao\"],\n",
    "    ).astype(str)\n",
    "except Exception:\n",
    "    def fallback_rating(val):\n",
    "        if pd.isna(val):\n",
    "            return \"Chua xac dinh\"\n",
    "        if val < 5.0:\n",
    "            return \"Thap (< 5.0)\"\n",
    "        elif val < 7.0:\n",
    "            return \"Trung binh (5.0 - 6.9)\"\n",
    "        else:\n",
    "            return \"Cao (>= 7.0)\"\n",
    "    fact_hieu_suat[\"NhomDiemDanhGia\"] = fact_hieu_suat[\"DiemDanhGiaTB\"].apply(fallback_rating)\n",
    "\n",
    "# 4. Phân nhóm độ phổ biến (NhomDoPhoBien)\n",
    "try:\n",
    "    fact_hieu_suat[\"NhomDoPhoBien\"] = pd.qcut(\n",
    "        fact_hieu_suat[\"DoPhoBien\"],\n",
    "        q=[0, 0.33, 0.66, 1.0],\n",
    "        labels=[\"Thap\", \"Trung binh\", \"Cao\"],\n",
    "    ).astype(str)\n",
    "except Exception:\n",
    "    def fallback_popularity(val):\n",
    "        if pd.isna(val):\n",
    "            return \"Chua xac dinh\"\n",
    "        if val < 1.0:\n",
    "            return \"Thap (< 1.0)\"\n",
    "        elif val < 5.0:\n",
    "            return \"Trung binh (1.0 - 4.9)\"\n",
    "        else:\n",
    "            return \"Cao (>= 5.0)\"\n",
    "    fact_hieu_suat[\"NhomDoPhoBien\"] = fact_hieu_suat[\"DoPhoBien\"].apply(fallback_popularity)\n",
    "\n",
    "# 5. Phân nhóm thời lượng (NhomThoiLuong) dùng ThoiLuongPhanTich\n",
    "try:\n",
    "    valid_runtime = fact_hieu_suat[\"ThoiLuongPhanTich\"].dropna()\n",
    "    if len(valid_runtime.unique()) >= 3:\n",
    "        runtime_cats = pd.qcut(valid_runtime, q=[0, 0.33, 0.66, 1.0], labels=[\"Ngan\", \"Trung binh\", \"Dai\"])\n",
    "        fact_hieu_suat[\"NhomThoiLuong\"] = runtime_cats.reindex(fact_hieu_suat.index).astype(str).fillna(\"Chua xac dinh\")\n",
    "    else:\n",
    "        raise ValueError(\"Khong du gia tri duy nhat\")\n",
    "except Exception:\n",
    "    def fallback_runtime(val):\n",
    "        if pd.isna(val):\n",
    "            return \"Chua xac dinh\"\n",
    "        if val < 60:\n",
    "            return \"Phim ngan (< 60')\"\n",
    "        elif val < 120:\n",
    "            return \"Phim tieu chuan (60' - 119')\"\n",
    "        else:\n",
    "            return \"Phim dai (>= 120')\"\n",
    "    fact_hieu_suat[\"NhomThoiLuong\"] = fact_hieu_suat[\"ThoiLuongPhanTich\"].apply(fallback_runtime)\n",
    "\n",
    "# 6. Phân nhóm doanh thu (NhomDoanhThu) dùng DoanhThuPhanTich\n",
    "try:\n",
    "    valid_rev = fact_hieu_suat[\"DoanhThuPhanTich\"].dropna()\n",
    "    if len(valid_rev.unique()) >= 3:\n",
    "        rev_cats = pd.qcut(valid_rev, q=[0, 0.33, 0.66, 1.0], labels=[\"Thap\", \"Trung binh\", \"Cao\"])\n",
    "        fact_hieu_suat[\"NhomDoanhThu\"] = rev_cats.reindex(fact_hieu_suat.index).astype(str).fillna(\"Chua xac dinh\")\n",
    "    else:\n",
    "        raise ValueError(\"Khong du gia tri duy nhat\")\n",
    "except Exception:\n",
    "    def fallback_revenue(val):\n",
    "        if pd.isna(val):\n",
    "            return \"Chua xac dinh\"\n",
    "        if val < 2000000:\n",
    "            return \"Thap (< 2M)\"\n",
    "        elif val < 15000000:\n",
    "            return \"Trung binh (2M - 15M)\"\n",
    "        else:\n",
    "            return \"Cao (>= 15M)\"\n",
    "    fact_hieu_suat[\"NhomDoanhThu\"] = fact_hieu_suat[\"DoanhThuPhanTich\"].apply(fallback_revenue)\n",
    "\n",
    "print(f\"Kích thước bảng FactHieuSuatPhim: {fact_hieu_suat.shape}\")\n",
    "display(fact_hieu_suat.head())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 4.3. Tạo bảng DimThoiGian\n",
    "\n",
    "Bảng `DimThoiGian` được xây dựng từ thuộc tính ngày phát hành (`NgayPhatHanh`) duy nhất, chứa các thuộc tính phân rã thời gian bao gồm: `NgayPhatHanh`, `Nam`, `Thang`, `Quy`, `ThapKy` và `GiaiDoan` (phân loại thành các nhóm giai đoạn: 2000-2009, 2010-2014, 2015-2019, 2020-2025)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Trích xuất danh sách ngày phát hành duy nhất và không bị thiếu\n",
    "dim_thoi_gian = filtered_df[[\"NgayPhatHanh\"]].dropna().drop_duplicates().copy()\n",
    "\n",
    "# Chuyển đổi ngày phát hành sang datetime để phân rã các thuộc tính thời gian\n",
    "dim_thoi_gian[\"NgayPhatHanh_dt\"] = pd.to_datetime(dim_thoi_gian[\"NgayPhatHanh\"])\n",
    "dim_thoi_gian[\"Nam\"] = dim_thoi_gian[\"NgayPhatHanh_dt\"].dt.year.astype(int)\n",
    "dim_thoi_gian[\"Thang\"] = dim_thoi_gian[\"NgayPhatHanh_dt\"].dt.month.astype(int)\n",
    "dim_thoi_gian[\"Quy\"] = dim_thoi_gian[\"NgayPhatHanh_dt\"].dt.quarter.astype(int)\n",
    "dim_thoi_gian[\"ThapKy\"] = (dim_thoi_gian[\"Nam\"] // 10 * 10).astype(str) + \"s\"\n",
    "\n",
    "\n",
    "# Hàm phân chia giai đoạn\n",
    "def get_giai_doan(year):\n",
    "    if 2000 <= year <= 2009:\n",
    "        return \"2000-2009\"\n",
    "    elif 2010 <= year <= 2014:\n",
    "        return \"2010-2014\"\n",
    "    elif 2015 <= year <= 2019:\n",
    "        return \"2015-2019\"\n",
    "    elif 2020 <= year <= 2025:\n",
    "        return \"2020-2025\"\n",
    "    return \"Khac\"\n",
    "\n",
    "\n",
    "dim_thoi_gian[\"GiaiDoan\"] = dim_thoi_gian[\"Nam\"].apply(get_giai_doan)\n",
    "\n",
    "# Định dạng cột ngày phát hành về chuỗi YYYY-MM-DD để dễ liên kết trong Power BI\n",
    "dim_thoi_gian[\"NgayPhatHanh\"] = dim_thoi_gian[\"NgayPhatHanh_dt\"].dt.strftime(\"%Y-%m-%d\")\n",
    "\n",
    "# Loại bỏ cột datetime phụ và giữ lại các cột cần thiết\n",
    "dim_thoi_gian = dim_thoi_gian[[\"NgayPhatHanh\", \"Nam\", \"Thang\", \"Quy\", \"ThapKy\", \"GiaiDoan\"]]\n",
    "\n",
    "# Format lại ngày phát hành trong fact table về định dạng tương tự\n",
    "if \"NgayPhatHanh\" in fact_hieu_suat.columns:\n",
    "    fact_hieu_suat[\"NgayPhatHanh\"] = pd.to_datetime(fact_hieu_suat[\"NgayPhatHanh\"]).dt.strftime(\"%Y-%m-%d\")\n",
    "\n",
    "print(f\"Kích thước bảng DimThoiGian: {dim_thoi_gian.shape}\")\n",
    "display(dim_thoi_gian.head())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 4.4. Tạo bảng DimQuocGia và BridgePhimQuocGia\n",
    "\n",
    "- **DimQuocGia**: Được thiết lập thủ công chứa danh mục 3 quốc gia nghiên cứu: Việt Nam (`VN`), Hàn Quốc (`KR`), và Trung Quốc (`CN`).\n",
    "- **BridgePhimQuocGia**: Được xây dựng bằng cách phân rã (explode) cột danh sách quốc gia được chọn thật sự (`QuocGiaDuocChon`) của từng bộ phim để hỗ trợ liên kết nhiều-nhiều giữa phim và quốc gia. Một phim thuộc nhiều quốc gia nghiên cứu sẽ được tách thành nhiều dòng tương ứng, và loại bỏ trùng lặp cặp khóa `MaPhim - MaQuocGia`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Tạo bảng DimQuocGia thủ công\n",
    "dim_quoc_gia = pd.DataFrame([\n",
    "    {\"MaQuocGia\": \"VN\", \"TenQuocGia\": \"Vietnam\", \"KhuVuc\": \"DongNamA\"},\n",
    "    {\"MaQuocGia\": \"KR\", \"TenQuocGia\": \"South Korea\", \"KhuVuc\": \"DongA\"},\n",
    "    {\"MaQuocGia\": \"CN\", \"TenQuocGia\": \"China\", \"KhuVuc\": \"DongA\"}\n",
    "])\n",
    "\n",
    "# 2. Tạo bảng BridgePhimQuocGia từ QuocGiaDuocChon\n",
    "bridge_quoc_gia = filtered_df[[\"MaPhim\", \"QuocGiaDuocChon\"]].copy()\n",
    "\n",
    "# Parse lại list nếu QuocGiaDuocChon bị lưu ở dạng chuỗi text biểu diễn list\n",
    "bridge_quoc_gia[\"QuocGiaDuocChon\"] = bridge_quoc_gia[\"QuocGiaDuocChon\"].apply(\n",
    "    lambda x: ast.literal_eval(x) if isinstance(x, str) else x\n",
    ")\n",
    "\n",
    "# Phân rã list thành nhiều dòng\n",
    "bridge_quoc_gia = bridge_quoc_gia.explode(\"QuocGiaDuocChon\")\n",
    "bridge_quoc_gia = bridge_quoc_gia.dropna(subset=[\"QuocGiaDuocChon\"])\n",
    "\n",
    "# Map quốc gia sang mã quốc gia tương ứng\n",
    "country_map = {\n",
    "    \"Vietnam\": \"VN\",\n",
    "    \"South Korea\": \"KR\",\n",
    "    \"China\": \"CN\"\n",
    "}\n",
    "bridge_quoc_gia[\"MaQuocGia\"] = bridge_quoc_gia[\"QuocGiaDuocChon\"].map(country_map)\n",
    "\n",
    "# Giữ lại cột và loại bỏ duplicate\n",
    "bridge_quoc_gia = bridge_quoc_gia[[\"MaPhim\", \"MaQuocGia\"]].dropna().drop_duplicates()\n",
    "\n",
    "print(f\"Kích thước bảng DimQuocGia: {dim_quoc_gia.shape}\")\n",
    "display(dim_quoc_gia)\n",
    "\n",
    "print(f\"\\nKích thước bảng BridgePhimQuocGia: {bridge_quoc_gia.shape}\")\n",
    "display(bridge_quoc_gia.head())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 4.5. Tạo bảng DimTheLoai và BridgePhimTheLoai\n",
    "\n",
    "- **DimTheLoai**: Được tạo bằng cách thu thập và phân tách toàn bộ thể loại phim từ thuộc tính `TheLoai` trong dữ liệu gốc. Các thể loại được giữ nguyên ngôn ngữ gốc (không dịch). Mã thể loại (`MaTheLoai`) được tự động đánh dạng `G001`, `G002`, `G003`... và loại bỏ trùng lặp thể loại.\n",
    "- **BridgePhimTheLoai**: Bảng liên kết trung gian chứa các cặp `MaPhim - MaTheLoai` để mô tả các thể loại của từng bộ phim, hỗ trợ mối quan hệ nhiều-nhiều và không bị trùng lặp cặp khóa."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def parse_genres(value):\n",
    "    \"\"\"Phân tách thể loại phim từ dạng list, chuỗi JSON hoặc text thường.\"\"\"\n",
    "    if _is_missing(value):\n",
    "        return []\n",
    "    parsed_value = _parse_json_like_text(value)\n",
    "    genres = []\n",
    "\n",
    "    def collect_genres(item):\n",
    "        if _is_missing(item):\n",
    "            return\n",
    "        if isinstance(item, dict):\n",
    "            name = item.get(\"name\")\n",
    "            if name:\n",
    "                genres.append(str(name).strip())\n",
    "            return\n",
    "        if isinstance(item, list):\n",
    "            for child_item in item:\n",
    "                collect_genres(child_item)\n",
    "            return\n",
    "        if isinstance(item, str):\n",
    "            text = item.strip()\n",
    "            if not text:\n",
    "                return\n",
    "            parsed_text = _parse_json_like_text(text)\n",
    "            if parsed_text is not text:\n",
    "                collect_genres(parsed_text)\n",
    "                return\n",
    "            for name in re.split(r\"[,;/|]\", text):\n",
    "                clean_name = name.strip()\n",
    "                if clean_name:\n",
    "                    genres.append(clean_name)\n",
    "\n",
    "    collect_genres(parsed_value)\n",
    "    # Loại trùng lặp và loại trừ các thể loại rỗng\n",
    "    return list(dict.fromkeys([g for g in genres if g]))\n",
    "\n",
    "\n",
    "# Thu thập toàn bộ thể loại xuất hiện\n",
    "all_genres_list = []\n",
    "for val in filtered_df[\"TheLoai\"].dropna():\n",
    "    all_genres_list.extend(parse_genres(val))\n",
    "\n",
    "# Tạo danh mục thể loại duy nhất, sắp xếp chữ cái\n",
    "unique_genres = sorted(list(set(all_genres_list)))\n",
    "\n",
    "# Tạo bảng DimTheLoai\n",
    "dim_the_loai = pd.DataFrame({\n",
    "    \"MaTheLoai\": [f\"G{i:03d}\" for i in range(1, len(unique_genres) + 1)],\n",
    "    \"TenTheLoai\": unique_genres\n",
    "})\n",
    "\n",
    "# 2. Tạo bảng BridgePhimTheLoai\n",
    "bridge_the_loai_data = []\n",
    "genre_to_id = dict(zip(dim_the_loai[\"TenTheLoai\"], dim_the_loai[\"MaTheLoai\"]))\n",
    "\n",
    "for _, row in filtered_df.iterrows():\n",
    "    ma_phim = row[\"MaPhim\"]\n",
    "    movie_genres = parse_genres(row[\"TheLoai\"])\n",
    "    for g in movie_genres:\n",
    "        ma_the_loai = genre_to_id.get(g)\n",
    "        if ma_the_loai:\n",
    "            bridge_the_loai_data.append({\"MaPhim\": ma_phim, \"MaTheLoai\": ma_the_loai})\n",
    "\n",
    "bridge_the_loai = pd.DataFrame(bridge_the_loai_data)\n",
    "\n",
    "# Đảm bảo không trùng lặp cặp khóa MaPhim - MaTheLoai và không có giá trị null\n",
    "bridge_the_loai = bridge_the_loai.dropna().drop_duplicates()\n",
    "\n",
    "print(f\"Kích thước bảng DimTheLoai: {dim_the_loai.shape}\")\n",
    "display(dim_the_loai.head())\n",
    "\n",
    "print(f\"\\nKích thước bảng BridgePhimTheLoai: {bridge_the_loai.shape}\")\n",
    "display(bridge_the_loai.head())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Kiểm tra và xuất dữ liệu đầu ra"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 5.1. Kiểm tra khóa chính, khóa ngoại và duplicate\n",
    "\n",
    "Kiểm tra tính toàn vẹn dữ liệu trước khi xuất ra các tệp CSV. Code thực hiện kiểm tra kích thước các bảng, số lượng trùng lặp, giá trị thiếu ở khóa chính/khóa ngoại, tính duy nhất của khóa chính, tính hợp lệ của tất cả các mối quan hệ khóa ngoại (Fact/Bridge đến Dim) và in kết quả kiểm tra rõ ràng dạng `PASSED`/`FAILED`. Ngoài ra, in các phân bố dữ liệu bổ sung để phục vụ báo cáo."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "print('=' * 60)\n",
    "print('KIỂM TRA CHẤT LƯỢNG CÁC BẢNG ĐẦU RA')\n",
    "print('=' * 60)\n",
    "\n",
    "# 1. In kích thước của từng bảng\n",
    "print('\\n1. Kích thước (Shape) của các bảng:')\n",
    "print(f'  - DimPhim:             {dim_phim.shape}')\n",
    "print(f'  - FactHieuSuatPhim:    {fact_hieu_suat.shape}')\n",
    "print(f'  - DimThoiGian:         {dim_thoi_gian.shape}')\n",
    "print(f'  - DimQuocGia:          {dim_quoc_gia.shape}')\n",
    "print(f'  - BridgePhimQuocGia:   {bridge_quoc_gia.shape}')\n",
    "print(f'  - DimTheLoai:          {dim_the_loai.shape}')\n",
    "print(f'  - BridgePhimTheLoai:   {bridge_the_loai.shape}')\n",
    "\n",
    "# 2. Kiểm tra Null ở khóa chính / khóa ngoại\n",
    "print('\\n2. Số lượng giá trị thiếu (Null) ở các cột khóa:')\n",
    "print(f'  - DimPhim[MaPhim]:                     {dim_phim[\"MaPhim\"].isna().sum()}')\n",
    "print(f'  - FactHieuSuatPhim[MaPhim]:            {fact_hieu_suat[\"MaPhim\"].isna().sum()}')\n",
    "print(f'  - FactHieuSuatPhim[NgayPhatHanh]:      {fact_hieu_suat[\"NgayPhatHanh\"].isna().sum()}')\n",
    "print(f'  - DimThoiGian[NgayPhatHanh]:           {dim_thoi_gian[\"NgayPhatHanh\"].isna().sum()}')\n",
    "print(f'  - BridgePhimQuocGia[MaPhim]:           {bridge_quoc_gia[\"MaPhim\"].isna().sum()}')\n",
    "print(f'  - BridgePhimQuocGia[MaQuocGia]:        {bridge_quoc_gia[\"MaQuocGia\"].isna().sum()}')\n",
    "print(f'  - BridgePhimTheLoai[MaPhim]:           {bridge_the_loai[\"MaPhim\"].isna().sum()}')\n",
    "print(f'  - BridgePhimTheLoai[MaTheLoai]:        {bridge_the_loai[\"MaTheLoai\"].isna().sum()}')\n",
    "\n",
    "# 3. Kiểm tra Duplicate ở từng bảng\n",
    "print('\\n3. Số dòng trùng lặp (Duplicate) trong từng bảng:')\n",
    "print(f'  - DimPhim:             {dim_phim.duplicated().sum()}')\n",
    "print(f'  - FactHieuSuatPhim:    {fact_hieu_suat.duplicated().sum()}')\n",
    "print(f'  - DimThoiGian:         {dim_thoi_gian.duplicated().sum()}')\n",
    "print(f'  - DimQuocGia:          {dim_quoc_gia.duplicated().sum()}')\n",
    "print(f'  - BridgePhimQuocGia (cặp khóa): {bridge_quoc_gia.duplicated(subset=[\"MaPhim\", \"MaQuocGia\"]).sum()}')\n",
    "print(f'  - BridgePhimTheLoai (cặp khóa): {bridge_the_loai.duplicated(subset=[\"MaPhim\", \"MaTheLoai\"]).sum()}')\n",
    "\n",
    "# 4. Kiểm tra tính toàn vẹn và khóa ngoại (Integrity Checks)\n",
    "print('\\n4. Kết quả kiểm tra tính toàn vẹn (PASSED/FAILED):')\n",
    "\n",
    "# Khóa chính DimPhim[MaPhim] unique\n",
    "is_dim_phim_pk_unique = dim_phim['MaPhim'].is_unique\n",
    "print(f'  - DimPhim[MaPhim] unique: {\"PASSED\" if is_dim_phim_pk_unique else \"FAILED\"}')\n",
    "\n",
    "# Khóa ngoại FactHieuSuatPhim[MaPhim] tồn tại trong DimPhim\n",
    "fact_phim_diff = set(fact_hieu_suat['MaPhim']) - set(dim_phim['MaPhim'])\n",
    "print(f'  - FactHieuSuatPhim[MaPhim] tồn tại trong DimPhim: {\"PASSED\" if len(fact_phim_diff) == 0 else \"FAILED\"}')\n",
    "\n",
    "# Khóa ngoại BridgePhimQuocGia[MaPhim] tồn tại trong DimPhim\n",
    "bridge_qg_phim_diff = set(bridge_quoc_gia['MaPhim']) - set(dim_phim['MaPhim'])\n",
    "print(f'  - BridgePhimQuocGia[MaPhim] tồn tại trong DimPhim: {\"PASSED\" if len(bridge_qg_phim_diff) == 0 else \"FAILED\"}')\n",
    "\n",
    "# Khóa ngoại BridgePhimTheLoai[MaPhim] tồn tại trong DimPhim\n",
    "bridge_tl_phim_diff = set(bridge_the_loai['MaPhim']) - set(dim_phim['MaPhim'])\n",
    "print(f'  - BridgePhimTheLoai[MaPhim] tồn tại trong DimPhim: {\"PASSED\" if len(bridge_tl_phim_diff) == 0 else \"FAILED\"}')\n",
    "\n",
    "# Khóa ngoại BridgePhimQuocGia[MaQuocGia] tồn tại trong DimQuocGia\n",
    "bridge_qg_code_diff = set(bridge_quoc_gia['MaQuocGia']) - set(dim_quoc_gia['MaQuocGia'])\n",
    "print(f'  - BridgePhimQuocGia[MaQuocGia] tồn tại trong DimQuocGia: {\"PASSED\" if len(bridge_qg_code_diff) == 0 else \"FAILED\"}')\n",
    "\n",
    "# Khóa ngoại BridgePhimTheLoai[MaTheLoai] tồn tại trong DimTheLoai\n",
    "bridge_tl_code_diff = set(bridge_the_loai['MaTheLoai']) - set(dim_the_loai['MaTheLoai'])\n",
    "print(f'  - BridgePhimTheLoai[MaTheLoai] tồn tại trong DimTheLoai: {\"PASSED\" if len(bridge_tl_code_diff) == 0 else \"FAILED\"}')\n",
    "\n",
    "# 5. In số phim theo quốc gia và năm phát hành\n",
    "print('\\n5. Số phim theo quốc gia mục tiêu (tính từ BridgePhimQuocGia):')\n",
    "qg_counts = bridge_quoc_gia.merge(dim_quoc_gia, on='MaQuocGia')['TenQuocGia'].value_counts()\n",
    "print(qg_counts)\n",
    "\n",
    "print('\\n6. Số phim theo năm phát hành:')\n",
    "year_counts = fact_hieu_suat['NamPhatHanh'].value_counts().sort_index()\n",
    "print(year_counts.to_string())\n",
    "\n",
    "# 6. In top 10 thể loại nhiều phim nhất\n",
    "print('\\n7. Top 10 thể loại nhiều phim nhất:')\n",
    "tl_counts = bridge_the_loai.merge(dim_the_loai, on='MaTheLoai')['TenTheLoai'].value_counts().head(10)\n",
    "print(tl_counts)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 5.2. Xuất các file CSV cho Power BI\n",
    "\n",
    "Xuất 7 bảng quan hệ đã chuẩn bị sang các tệp CSV riêng biệt nằm trong thư mục `data/processed/powerbi/` phục vụ import trực tiếp vào Power BI. Định dạng ghi tệp đảm bảo các yêu cầu kỹ thuật:\n",
    "- `encoding=\"utf-8-sig\"` (để hiển thị đúng ký tự Unicode tiếng Việt khi import vào Power BI).\n",
    "- `index=False` (không ghi cột số thứ tự dòng).\n",
    "- `lineterminator=\"\\n\"` (đảm bảo xuống dòng ổn định)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cấu hình tham số xuất\n",
    "export_params = {\n",
    "    \"index\": False,\n",
    "    \"encoding\": \"utf-8-sig\",\n",
    "    \"lineterminator\": \"\\n\",\n",
    "}\n",
    "\n",
    "# Xuất 7 file CSV\n",
    "dim_phim.to_csv(os.path.join(POWERBI_DIR, \"DimPhim.csv\"), **export_params)\n",
    "fact_hieu_suat.to_csv(os.path.join(POWERBI_DIR, \"FactHieuSuatPhim.csv\"), **export_params)\n",
    "dim_thoi_gian.to_csv(os.path.join(POWERBI_DIR, \"DimThoiGian.csv\"), **export_params)\n",
    "dim_quoc_gia.to_csv(os.path.join(POWERBI_DIR, \"DimQuocGia.csv\"), **export_params)\n",
    "bridge_quoc_gia.to_csv(os.path.join(POWERBI_DIR, \"BridgePhimQuocGia.csv\"), **export_params)\n",
    "dim_the_loai.to_csv(os.path.join(POWERBI_DIR, \"DimTheLoai.csv\"), **export_params)\n",
    "bridge_the_loai.to_csv(os.path.join(POWERBI_DIR, \"BridgePhimTheLoai.csv\"), **export_params)\n",
    "\n",
    "print(f\"Đã xuất toàn bộ 7 tệp dữ liệu quan hệ vào thư mục: {POWERBI_DIR}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 5.3. Mô tả data model dự kiến trong Power BI\n",
    "\n",
    "Dưới đây là thiết kế mối quan hệ (relationship) giữa các bảng trong mô hình dữ liệu (Star Schema kết hợp Bridge tables) phục vụ dashboard Power BI:\n",
    "\n",
    "- **DimPhim[MaPhim]** `1 — *` **FactHieuSuatPhim[MaPhim]** (Mối quan hệ 1 - Nhiều để map thông tin mô tả phim với các chỉ số hiệu suất của phim).\n",
    "- **DimPhim[MaPhim]** `1 — *` **BridgePhimQuocGia[MaPhim]** (Mối quan hệ 1 - Nhiều để phân rã liên kết quốc gia).\n",
    "- **DimQuocGia[MaQuocGia]** `1 — *` **BridgePhimQuocGia[MaQuocGia]** (Mối quan hệ 1 - Nhiều để map mã quốc gia sang tên đầy đủ và khu vực).\n",
    "- **DimPhim[MaPhim]** `1 — *` **BridgePhimTheLoai[MaPhim]** (Mối quan hệ 1 - Nhiều để phân rã liên kết thể loại).\n",
    "- **DimTheLoai[MaTheLoai]** `1 — *` **BridgePhimTheLoai[MaTheLoai]** (Mối quan hệ 1 - Nhiều để map mã thể loại sang tên thể loại gốc).\n",
    "- **DimThoiGian[NgayPhatHanh]** `1 — *` **FactHieuSuatPhim[NgayPhatHanh]** (Mối quan hệ 1 - Nhiều giúp phân tích hiệu suất phim theo năm, tháng, quý, giai đoạn)."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 5.4. Kết luận tiền xử lý\n",
    "\n",
    "Quy trình tiền xử lý dữ liệu TMDB Movies A–Z đã hoàn thành tốt đẹp với các kết quả chính:\n",
    "- **Lọc dữ liệu chính xác**: Chỉ giữ các phim thuộc 3 quốc gia nghiên cứu (Việt Nam, Hàn Quốc, Trung Quốc) phát hành trong giai đoạn 2000–2025, trạng thái đã phát hành (`Released`) và có thông tin chấm điểm hợp lệ.\n",
    "- **Chuẩn hóa ngôn ngữ**: Toàn bộ tên cột được đưa về tiếng Việt không dấu. Các chuỗi text được làm sạch ký tự xuống dòng đặc biệt để tránh lỗi hiển thị.\n",
    "- **Giữ toàn vẹn thông tin**: Không xóa dòng thiếu doanh thu/ngân sách/thời lượng, thay vào đó sử dụng cờ chất lượng dữ liệu.\n",
    "- **Tạo mô hình dữ liệu quan hệ**: Dữ liệu sạch đã được tách thành 7 bảng Dim/Fact/Bridge theo đúng chuẩn và lưu trữ trong thư mục `data/processed/powerbi/`, sẵn sàng để kết nối trực tiếp vào Power BI."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbformat_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

# Ghi tệp preprocessing.ipynb
notebook_path = "notebooks/preprocessing.ipynb"
with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook_content, f, ensure_ascii=False, indent=1)

print(f"Build notebook successfully at {notebook_path}!")
